### ISSUE TITLE
tfsec default version is broken (again)

### ISSUE THREAD

**Issue by marcus-crane** [aquasecurity/tfsec-sarif-action#30]
Hi there,

The combination of #27 and #28 is now returning `https://api.github.com/repos/aquasecurity/tfsec/releaseslatest` which is also not a valid URL.

I think only one of these PRs should have been merged, not both.

For reference, the above is when using the following configuration:

```yaml
[...]
      - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif #Static Analysis Results Interchange Format (SARIF)
        env:
          github_token: ${{ secrets.github_token }}
```

As a side note, I think this repo should run its own action as a check so you can have visibility into its current working state 😉 

Thanks!
