### ISSUE TITLE
does the action work?

### ISSUE THREAD

**Issue by ghost** [aquasecurity/tfsec-sarif-action#46]
I setup the action:

```
      - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@master
        with:
          sarif_file: kk.sarif
          soft_fail: true
```

the content to the file:

```
{
  "version": "2.1.0",
  "$schema": "https://json.schemastore.org/sarif-2.1.0-rtm.5.json",
  "runs": [
    {
      "tool": {
        "driver": {
          "informationUri": "https://github.com/aquasecurity/defsec",
          "name": "defsec",
          "rules": []
        }
      },
      "results": []
    }
  ]
```
