### ISSUE TITLE
Feature: Support passing config file in the action

### ISSUE THREAD

**Issue by nandhae** [aquasecurity/tfsec-sarif-action#9]
**Kind:** Feature

**Description:** Requesting to add support for passing config file in the action since it would be easy to pass ignore values and other configuration via a config file.
Expected behaviour example:

```
- name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          config_file: ./tfsec.yml
```
